export enum ApiNamesConstants {
    INVITE_USER = "INVITE_USER",
    TOKEN_VERIFY = "TOKEN_VERIFY",
    TOKEN_SIGN_FOR_INVITED_USESR="TOKEN_SIGN_FOR_INVITED_USESR",
    FETCH_ROLES_PERMISSIONS="FETCH_ROLES_PERMISSIONS",
    VERIFY_TOKEN="VERIFY_TOKEN",
    NORMAL_SIGNUP="NORMAL_SIGNUP"
}